In [1]:
import matplotlib.pyplot as plt 
import numpy as np 
import pandas as pd 
import seaborn as sbn 
import random 
from mpl_toolkits.mplot3d import axes3d
#% matplotlib inline

In [2]:
datasetcovid=pd.read_excel('dataset.xlsx')

In [3]:
pd.set_option('display.max_row',datasetcovid.shape[1])

# 2.  Le Pre- Proccessing

In [4]:
#une nouvelle copie du dataset original
data_preproccessing=datasetcovid.copy()

In [5]:
# la 1ere de chose c'est de selectionner les variables qu'on a juge utiles dans le EDA
missing_rate=data_preproccessing.isna().sum(axis=0)/data_preproccessing.shape[0]
#creons la liste des variables les plus importantes
blood_columns2=list(data_preproccessing.columns[(missing_rate<0.9) & (missing_rate>0.88)])
viral_columns2=list(data_preproccessing.columns[(missing_rate<0.80) & (missing_rate>0.75)])
key_columns=['Patient age quantile','SARS-Cov-2 exam result']
#on a elimine toute les variables avec au plus 90% des variables manquantes

In [6]:
data_preproccessing=data_preproccessing[key_columns + blood_columns2 + viral_columns2]

In [7]:
pd.set_option('display.max_column',data_preproccessing.shape[1])#permet d'afficher toute colonne
data_preproccessing.head()

,Patient age quantile,SARS-Cov-2 exam result,Hematocrit,Hemoglobin,Platelets,Mean platelet volume,Red blood Cells,Lymphocytes,Mean corpuscular hemoglobin concentration (MCHC),Leukocytes,Basophils,Mean corpuscular hemoglobin (MCH),Eosinophils,Mean corpuscular volume (MCV),Monocytes,Red blood cell distribution width (RDW),Respiratory Syncytial Virus,Influenza A,Influenza B,Parainfluenza 1,CoronavirusNL63,Rhinovirus/Enterovirus,Coronavirus HKU1,Parainfluenza 3,Chlamydophila pneumoniae,Adenovirus,Parainfluenza 4,Coronavirus229E,CoronavirusOC43,Inf A H1N1 2009,Bordetella pertussis,Metapneumovirus,Parainfluenza 2
0,13,negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17,negative,0.236515,-0.02234,-0.517413,0.010677,0.102004,0.318366,-0.95079,-0.09461,-0.223767,-0.292269,1.482158,0.166192,0.357547,-0.625073,not_detected,not_detected,not_detected,not_detected,not_detected,detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected
2,8,negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,15,negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not_detected,not_detected,not_detected,not_detected,not_detected,detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected

In [8]:
#import train_test_split depuis le module model_selection.
from sklearn.model_selection import train_test_split
trainset,testset= train_test_split(data_preproccessing,test_size=0.2,random_state=0)
testset.head(3)

,Patient age quantile,SARS-Cov-2 exam result,Hematocrit,Hemoglobin,Platelets,Mean platelet volume,Red blood Cells,Lymphocytes,Mean corpuscular hemoglobin concentration (MCHC),Leukocytes,Basophils,Mean corpuscular hemoglobin (MCH),Eosinophils,Mean corpuscular volume (MCV),Monocytes,Red blood cell distribution width (RDW),Respiratory Syncytial Virus,Influenza A,Influenza B,Parainfluenza 1,CoronavirusNL63,Rhinovirus/Enterovirus,Coronavirus HKU1,Parainfluenza 3,Chlamydophila pneumoniae,Adenovirus,Parainfluenza 4,Coronavirus229E,CoronavirusOC43,Inf A H1N1 2009,Bordetella pertussis,Metapneumovirus,Parainfluenza 2
5113,7,negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2343,7,negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2552,1,negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
data_preproccessing.dropna(axis=0)

,Patient age quantile,SARS-Cov-2 exam result,Hematocrit,Hemoglobin,Platelets,Mean platelet volume,Red blood Cells,Lymphocytes,Mean corpuscular hemoglobin concentration (MCHC),Leukocytes,Basophils,Mean corpuscular hemoglobin (MCH),Eosinophils,Mean corpuscular volume (MCV),Monocytes,Red blood cell distribution width (RDW),Respiratory Syncytial Virus,Influenza A,Influenza B,Parainfluenza 1,CoronavirusNL63,Rhinovirus/Enterovirus,Coronavirus HKU1,Parainfluenza 3,Chlamydophila pneumoniae,Adenovirus,Parainfluenza 4,Coronavirus229E,CoronavirusOC43,Inf A H1N1 2009,Bordetella pertussis,Metapneumovirus,Parainfluenza 2
1,17,0,0.236515,-0.022340,-0.517413,0.010677,0.102004,0.318366,-0.950790,-0.094610,-0.223767,-0.292269,1.482158,0.166192,0.357547,-0.625073,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,1,0,-1.571682,-0.774212,1.429667,-1.672222,-0.850035,-0.005738,3.331071,0.364550,-0.223767,0.178175,1.018625,-1.336024,0.068652,-0.978899,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,9,0,-0.747693,-0.586244,-0.429480,-0.213711,-1.361315,-1.114514,0.542882,-0.884923,0.081693,1.746323,-0.666950,1.668409,1.276759,-1.067355,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
18,11,0,0.991838,0.792188,0.072992,-0.550290,0.542763,0.045436,-0.452899,-0.211488,-0.834685,0.334989,-0.709090,0.606842,-0.220244,0.171035,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,13,0,1.014726,0.854844,-0.178244,0.796029,0.489872,-0.730707,-0.353319,-0.075131,2.525365,0.544077,0.217977,0.767079,0.068652,0.171035,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5585,18,1,1.197836,1.356092,-1.911774,1.132609,0.384090,0.966573,0.841616,-0.834833,-0.529226,1.589509,-0.582671,1.307876,1.197969,-0.094334,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5602,19,0,0.190738,0.165628,-0.102873,0.908221,0.384090,-1.583611,-0.054585,-0.328365,-0.834685,-0.449085,0.892207,-0.474754,1.066653,0.347948,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5614,19,0,-0.289922,-0.523588,0.663397,-0.774677,0.754327,-1.532437,-1.050367,1.569499,0.081693,-2.174047,-0.540532,-1.976971,1.670707,0.967144,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5615,15,0,0.717175,1.105468,-0.492289,-0.213711,0.613284,0.002791,1.538664,-0.550988,-0.223767,0.700891,-0.709090,0.005955,0.909074,-1.155812,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5618,17,0,-3.242548,-2.779203,-1.773594,-0.550290,-3.318285,-1.830953,1.538664,-1.733675,-1.140144,2.059952,-0.582671,1.408024,1.381812,-0.448160,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
trainset.iloc[:,1].value_counts(normalize=True)*100,testset.iloc[:,1].value_counts(normalize=True)*100
#le proportion de chaque cas et bien respectee apres le decoupage

(SARS-Cov-2 exam result
 negative    90.099668
 positive     9.900332
 Name: proportion, dtype: float64,
 SARS-Cov-2 exam result
 negative    90.168291
 positive     9.831709
 Name: proportion, dtype: float64)

In [20]:
data_preproccessing.dropna(axis='index')

,Patient age quantile,SARS-Cov-2 exam result,Hematocrit,Hemoglobin,Platelets,Mean platelet volume,Red blood Cells,Lymphocytes,Mean corpuscular hemoglobin concentration (MCHC),Leukocytes,Basophils,Mean corpuscular hemoglobin (MCH),Eosinophils,Mean corpuscular volume (MCV),Monocytes,Red blood cell distribution width (RDW),Respiratory Syncytial Virus,Influenza A,Influenza B,Parainfluenza 1,CoronavirusNL63,Rhinovirus/Enterovirus,Coronavirus HKU1,Parainfluenza 3,Chlamydophila pneumoniae,Adenovirus,Parainfluenza 4,Coronavirus229E,CoronavirusOC43,Inf A H1N1 2009,Bordetella pertussis,Metapneumovirus,Parainfluenza 2
1,17,negative,0.236515,-0.022340,-0.517413,0.010677,0.102004,0.318366,-0.950790,-0.094610,-0.223767,-0.292269,1.482158,0.166192,0.357547,-0.625073,not_detected,not_detected,not_detected,not_detected,not_detected,detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected
8,1,negative,-1.571682,-0.774212,1.429667,-1.672222,-0.850035,-0.005738,3.331071,0.364550,-0.223767,0.178175,1.018625,-1.336024,0.068652,-0.978899,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected
15,9,negative,-0.747693,-0.586244,-0.429480,-0.213711,-1.361315,-1.114514,0.542882,-0.884923,0.081693,1.746323,-0.666950,1.668409,1.276759,-1.067355,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,detected,not_detected,not_detected,not_detected
18,11,negative,0.991838,0.792188,0.072992,-0.550290,0.542763,0.045436,-0.452899,-0.211488,-0.834685,0.334989,-0.709090,0.606842,-0.220244,0.171035,not_detected,not_detected,not_detected,not_detected,not_detected,detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected
28,13,negative,1.014726,0.854844,-0.178244,0.796029,0.489872,-0.730707,-0.353319,-0.075131,2.525365,0.544077,0.217977,0.767079,0.068652,0.171035,not_detected,not_detected,not_detected,not_detected,not_detected,detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5585,18,positive,1.197836,1.356092,-1.911774,1.132609,0.384090,0.966573,0.841616,-0.834833,-0.529226,1.589509,-0.582671,1.307876,1.197969,-0.094334,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected
5602,19,negative,0.190738,0.165628,-0.102873,0.908221,0.384090,-1.583611,-0.054585,-0.328365,-0.834685,-0.449085,0.892207,-0.474754,1.066653,0.347948,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected
5614,19,negative,-0.289922,-0.523588,0.663397,-0.774677,0.754327,-1.532437,-1.050367,1.569499,0.081693,-2.174047,-0.540532,-1.976971,1.670707,0.967144,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected
5615,15,negative,0.717175,1.105468,-0.492289,-0.213711,0.613284,0.002791,1.538664,-0.550988,-0.223767,0.700891,-0.709090,0.005955,0.909074,-1.155812,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected
5618,17,negative,-3.242548,-2.779203,-1.773594,-0.550290,-3.318285,-1.830953,1.538664,-1.733675,-1.140144,2.059952,-0.582671,1.408024,1.381812,-0.448160,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected,not_detected

### L'encodage
on a remarque que dans le type object il ya  differents categorie

In [10]:
#creons une fonction qui permet de faire l'encodage sur le train et le test
def encodage(data_preproccessing):
    #remplacons nos variables qualitalives par les varables quantitatives
    code={'positive':1,'negative':0,'detected':1,'not_detected':0}
    for col in data_preproccessing.select_dtypes('object'):
        data_preproccessing.loc[:,col]=data_preproccessing.loc[:,col].map(code)
    return data_preproccessing

In [11]:
#encodage(trainset)

In [24]:
# imputation

def imputation(dataframe):
    dataframe=encodage(dataframe)
    #ataframe.fillna(-999)
    #dataframe['']
    
    return dataframe.dropna(axis=0)

def preprocessing(dataframe):
    dataframe=encodage(dataframe)
    dataframe=imputation(dataframe)
    print(dataframe.shape)
    x,y=dataframe.drop(columns='SARS-Cov-2 exam result',axis='colums'),dataframe['SARS-Cov-2 exam result']
    print('la proportion cas apres le preprocessing est de: {} {}'.format('\n',y.value_counts(normalize=True)))
    return x,y

x_train,y_train=preprocessing(trainset)
#x_test,y_test=preprocessing(testset)

(0, 33)
la proportion cas apres le preprocessing est de:
 Series([], Name: proportion, dtype: float64)

In [21]:
imputation(data_preproccessing).shape

(362, 33)

In [13]:
x_train

Empty DataFrame
Columns: [Patient age quantile, Hematocrit, Hemoglobin, Platelets, Mean platelet volume , Red blood Cells, Lymphocytes, Mean corpuscular hemoglobin concentration (MCHC), Leukocytes, Basophils, Mean corpuscular hemoglobin (MCH), Eosinophils, Mean corpuscular volume (MCV), Monocytes, Red blood cell distribution width (RDW), Respiratory Syncytial Virus, Influenza A, Influenza B, Parainfluenza 1, CoronavirusNL63, Rhinovirus/Enterovirus, Coronavirus HKU1, Parainfluenza 3, Chlamydophila pneumoniae, Adenovirus, Parainfluenza 4, Coronavirus229E, CoronavirusOC43, Inf A H1N1 2009, Bordetella pertussis, Metapneumovirus, Parainfluenza 2]
Index: []

In [14]:
y_train.size

0

# Modelisation

In [15]:
#creons un arbre de decision 
from sklearn.tree import  DecisionTreeClassifier

la metrique F1 permet d'avoir un bon appercu entre le rapport de la precision et la sensibilite(recall) .la precision et la sensibilte se sont des metriques qui permettent de mesurer les proportions des erreurs de type 1 et de type 2(faut positive et faut negative) dans le dataset

In [16]:
#importons les differents metriques
from sklearn.metrics import f1_score, confusion_matrix,classification_report
from sklearn.model_selection import learning_curve#permet de voir si notre modele est en over ou endre fitting
model =DecisionTreeClassifier(random_state=0)

def evaluation(model):
    model.fit(x_train,y_train)
    score=model.score(x_train,y_train)
    y_prediction=model.predict(x_test)
    matrice_de_confusion=confusion_matrix(y_test,y_prediction)
    report=classification_report(y_test,y_prediction)
    #print(f'{matrice_de_confusion=}')
    print('la matrice de confusion \n {}'.format(matrice_de_confusion))
    print('{}'.format(report))
    
    #Essayons d'ameliorer le modele en tracant la courbe de validation enfin de bien comprendre notre modele.
    N,train_score,test_score=learning_curve(model,
                                            x_train,y_train,
                                           cv=4, scoring='f1',train_sizes=np.linspace(0.1,1,10))
    #tracons ls courbes
    plt.figure()
    plt.plot(N, train_score.mean(axis=1),color='b',label='le score sur le train')
             
    plt.plot(N, test_score.mean(axis=1),color='red',label='le score sur le test')
    plt.legend()

In [17]:
evaluation(model)

ValueError: Found array with 0 sample(s) (shape=(0, 32)) while a minimum of 1 is required by DecisionTreeClassifier.

d'apres le resultat du report on voit que avec le score recall sur 12 cas positive on a pu identifier que 2. Essayons d'ameliorer le modele en tracant la courbe de validation enfin de bien comprendre notre modele. on remarque directement que le modele est en overting car il a un score tres eleve en trainset un score a peine 50% sur le test.essayons de resoudre ce probleme par ex on peut fournir + de donnee au modele. en plus on dirait que plus on a de donnee plus le score du test augment. pour cela au lie d'utiliser le dropna qui reduire significativemnt le nombre de nos donnee, essayons une autre fonction d'imputation

le ccl :
- il faut tester des differents idees.
dans notre cas pour augmenter le score on a essayer d'augmenter la taille de nos donnees en lui remplacant le df.dropa() par un fillna(-999),   missing indicator. on  a aussi tester la selection des variables qui permet de resoudre le overfiting.

In [ ]:
#utilisoons l'attribut futur importance du modele pour choisr les meilleurs variables pour le stimatuer choisit
print(model.feature_importances_ )#chaque valeur du array est assossier a une colonne
#on peut injecter tout ca dans un tableau df 
pd.DataFrame(model.feature_importances_,index=x_train.columns).sort_values(by=0,ascending=True)

In [ ]:
#tracons un colorbar pour voir plus clair
plt.figure(figsize=(12,10))
pd.DataFrame(model.feature_importances_,index=x_train.columns).plot.bar()

dans le cas ou notre stimateur est un arbre de decision on voit que les variables de type sang qui sont plus important pour le model. c'est ne pas aussi surprenant car lors de l'exploration des donnee on a pu remarquer que les leukocytes, platelets varient significativement du cas positive et negative. a apartir du graphique on peut faire deux chose :
1. definr un seil avec Threshold en dessous du quel tte les variables seront eluminer.
2. eluminer toute les variables virals.

In [ ]:
x_train.std(axis=0)

In [ ]:
from sklearn.metrics import confusion_matrix
import pandas as pd

In [ ]:
groupe1=np.array([1,1,1,0,0,1,0,1,0,0,1]).reshape(11,1)
groupe2=np.array([1,0,1,1,0,1,0,1,1,0,1]).reshape(11,1)
groupe1.shape

In [ ]:
confusion_matrix(groupe1,groupe2)

In [ ]:
dat=pd.DataFrame(data=np.hstack((groupe1,groupe2)),columns=['valeur_reelle','prediction'])
dat

In [ ]:
pd.crosstab(dat.valeur_reelle,dat.prediction)

In [ ]:
arr1=np.array([153.6,156,150.2,158.5,154.9])
arr2=np.array([165.3,165.9,159.7,163.5,158])

In [ ]:
np.std(arr1),np.std(arr2)

In [ ]:
np.mean(arr1)

In [ ]:
np.mean(arr2)